M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu22.04.1} date Wed 12 Jul 2023 01:59:00 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-12T13:59:00-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1280
%
G90
G05
T1
X2.1783Y-2.3382
X2.6283Y-2.3382
T0
M30
